### ISSUE TITLE
pressing multiple keys simultaneously

### ISSUE THREAD

**Issue by d3xt3r01** [dornbirndevelops/nintendo-switch-controller-arduino#10]
Hello,

Can you give an example on how would one have multiple keys pressed at the same time ?

Thanks.

**Comment by dornbirndevelops** [comment]
Good question @d3xt3r01!

First you need to know how a single controller input state is represented.
```
aabbccddeeffgghh duration
aa = button high (01 = minus, 02 = plus, 04 = left stick press, 08 = right stick press, 10 = home, 20 = capture)
bb = button low (01 = Y, 02 = B, 04 = A, 08 = X, 10 = L, 20 = R, 40 = ZL, 80 = ZR)
cc = DPAD position (01-08 namely top top right right bottom right bottom bottom left, left, top left, center)
dd = left stick x direction
ee = left stick y direction
ff = right stick x direction
gg = right stick y direction
hh = unused (leave 00)
```

*aa* for example refers to the first two hexadecimal digits.

---

Let's assume we want to press the buttons A and B and Left Stick to the right:

Button A (=0x04) and B (=0x02) are both located in the position *bb*,
whereas the X direction of the Left Stick is in position *dd*.

Starting from the initial controller state
```
aabbccddeeffgghh <duration_ms>
0000088080808000 1000
```
we need to apply the bitwise OR operation for A and B
bb = 0x04 | 0x02 =  0x06

and since the left stick should be towards the right we also apply this one
dd = 0xFF

```
aabbccddeeffgghh <duration_ms>
000608FF80808000 1000
```

**Comment by dornbirndevelops** [comment]
i will close this issue for now. feel free to re-open it in case of an issue.
